// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jakeispkrvnzqgpemzum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impha2Vpc3BrcnZuenFncGVtenVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDUyNzcsImV4cCI6MjA2MTQyMTI3N30.zNJMFdXt6nZyXQJBH0oVTMA1yX1WYs6ts6IG498gJ5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);